---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
  namespace: ai-part-designer
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ai-part-designer
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: CHANGEME_USE_SECRET_MANAGER
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-user
  namespace: ai-part-designer
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ai-part-designer
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: CHANGEME_USE_SECRET_MANAGER
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secret
  namespace: ai-part-designer
  labels:
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/component: database-backup
    app.kubernetes.io/part-of: ai-part-designer
type: Opaque
stringData:
  ACCESS_KEY_ID: minio
  ACCESS_SECRET_KEY: CHANGEME_USE_SECRET_MANAGER
