{{- if .Values.createServiceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: celery
  labels:
    {{- include "ai-part-designer.worker.selectorLabels" . | nindent 4 }}
    {{- include "ai-part-designer.labels" . | nindent 4 }}
{{- end }}
