apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-worker-hpa
  labels:
    {{- include "ai-part-designer.worker.selectorLabels" . | nindent 4 }}
    {{- include "ai-part-designer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicas: {{ .Values.workerHpaMin }}
  maxReplicas: {{ .Values.workerHpaMax }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.workerCpuPercent }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.workerMemPercent }}
