{{- if .Values.createServiceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    {{- include "ai-part-designer.backend.selectorLabels" . | nindent 4 }}
    {{- include "ai-part-designer.labels" . | nindent 4 }}
{{- end }}
