apiVersion: 1
datasources:
- name: AIPartDesignerMetrics
  type: prometheus
  uid: pd_prometheus_main
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: false
  jsonData:
    timeInterval: 20s
    httpMethod: POST
    queryTimeout: 90s
    incrementalQuerying: true
    incrementalQueryOverlapWindow: 15m
