{{- if .Values.installPostgres }}
{{- if .Values.cloudnativePg.cluster.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secret
  labels:
    {{- include "ai-part-designer.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/component: database-backup
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.cloudnativePg.cluster.backup.s3.accessKeyId | default "minio" | quote }}
  ACCESS_SECRET_KEY: {{ .Values.cloudnativePg.cluster.backup.s3.secretAccessKey | default "CHANGEME_USE_SECRET_MANAGER" | quote }}
{{- end }}
{{- end }}
