---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: worker
        command: ["uv", "run", "celery", "-A", "app.worker.celery_app", "worker", "--loglevel=debug", "--concurrency=2"]
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: APP_ENV
          value: "development"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
