---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: celery
  namespace: ai-part-designer
  labels:
    app.kubernetes.io/name: celery
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: ai-part-designer
automountServiceAccountToken: false
