apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "ai-part-designer.frontend.selectorLabels" . | nindent 4 }}
    {{- include "ai-part-designer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "ai-part-designer.frontend.selectorLabels" . | nindent 4 }}
