# CAD v2 Schemas
#
# Pydantic models defining the structure of CAD designs.
# These schemas are validated before compilation to Build123d geometry.

from app.cad_v2.schemas.base import (
    Axis,
    BoundingBox,
    Dimension,
    Point2D,
    Point3D,
    Rotation,
    Tolerance,
    Unit,
    Vector3D,
)
from app.cad_v2.schemas.components import (
    ComponentCategory,
    ComponentDefinition,
    ComponentMount,
    ComponentRef,
    KeepoutZone,
    MountingHole,
    MountingType,
    PortDefinition,
    PortExposure,
    StandoffSpec,
    StandoffType,
)
from app.cad_v2.schemas.enclosure import (
    EnclosureSpec,
    LidSpec,
    LidType,
    MountingTabSpec,
    ScrewSpec,
    SnapFitSpec,
    VentilationSpec,
    WallSide,
    WallSpec,
)
from app.cad_v2.schemas.features import (
    BaseCutout,
    ButtonCutout,
    CircleCutout,
    CutoutShape,
    CutoutSpec,
    DisplayCutout,
    Feature,
    FeatureType,
    MountingHoleFeature,
    OvalCutout,
    PolygonCutout,
    PortCutout,
    RectangleCutout,
    SlotCutout,
    TextFeature,
    VentPattern,
)
from app.cad_v2.schemas.patterns import (
    CircularPattern,
    CustomPattern,
    GridPattern,
    LinearPattern,
    Pattern,
    PatternedFeature,
    PatternPresets,
    PatternType,
)
from app.cad_v2.schemas.spatial import (
    AbsolutePosition,
    AlignedPosition,
    Alignment2D,
    Alignment3D,
    AlignWithConstraint,
    CenterBetweenConstraint,
    DepthAlignment,
    HorizontalAlignment,
    LayoutHint,
    Margin,
    MaxDistanceConstraint,
    MinDistanceConstraint,
    Position,
    RelativePosition,
    SpatialConstraint,
    VerticalAlignment,
    WallPosition,
)

__all__ = [
    # Spatial types
    "AbsolutePosition",
    "AlignWithConstraint",
    "AlignedPosition",
    "Alignment2D",
    "Alignment3D",
    # Base types
    "Axis",
    # Feature types
    "BaseCutout",
    "BoundingBox",
    "ButtonCutout",
    "CenterBetweenConstraint",
    "CircleCutout",
    # Pattern types
    "CircularPattern",
    # Component types
    "ComponentCategory",
    "ComponentDefinition",
    "ComponentMount",
    "ComponentRef",
    "CustomPattern",
    "CutoutShape",
    "CutoutSpec",
    "DepthAlignment",
    "Dimension",
    "DisplayCutout",
    # Enclosure types
    "EnclosureSpec",
    "Feature",
    "FeatureType",
    "GridPattern",
    "HorizontalAlignment",
    "KeepoutZone",
    "LayoutHint",
    "LidSpec",
    "LidType",
    "LinearPattern",
    "Margin",
    "MaxDistanceConstraint",
    "MinDistanceConstraint",
    "MountingHole",
    "MountingHoleFeature",
    "MountingTabSpec",
    "MountingType",
    "OvalCutout",
    "Pattern",
    "PatternPresets",
    "PatternType",
    "PatternedFeature",
    "Point2D",
    "Point3D",
    "PolygonCutout",
    "PortCutout",
    "PortDefinition",
    "PortExposure",
    "Position",
    "RectangleCutout",
    "RelativePosition",
    "Rotation",
    "ScrewSpec",
    "SlotCutout",
    "SnapFitSpec",
    "SpatialConstraint",
    "StandoffSpec",
    "StandoffType",
    "TextFeature",
    "Tolerance",
    "Unit",
    "Vector3D",
    "VentPattern",
    "VentilationSpec",
    "VerticalAlignment",
    "WallPosition",
    "WallSide",
    "WallSpec",
]
