# CAD v2 Schemas
#
# Pydantic models defining the structure of CAD designs.
# These schemas are validated before compilation to Build123d geometry.

from app.cad_v2.schemas.base import (
    Axis,
    BoundingBox,
    Dimension,
    Point2D,
    Point3D,
    Rotation,
    Tolerance,
    Unit,
    Vector3D,
)
from app.cad_v2.schemas.components import (
    ComponentCategory,
    ComponentDefinition,
    ComponentMount,
    ComponentRef,
    KeepoutZone,
    MountingHole,
    MountingType,
    PortDefinition,
    PortExposure,
    StandoffSpec,
    StandoffType,
)
from app.cad_v2.schemas.enclosure import (
    EnclosureSpec,
    LidSpec,
    LidType,
    MountingTabSpec,
    ScrewSpec,
    SnapFitSpec,
    VentilationSpec,
    WallSide,
    WallSpec,
)
from app.cad_v2.schemas.features import (
    BaseCutout,
    ButtonCutout,
    CircleCutout,
    CutoutShape,
    CutoutSpec,
    DisplayCutout,
    Feature,
    FeatureType,
    MountingHoleFeature,
    OvalCutout,
    PolygonCutout,
    PortCutout,
    RectangleCutout,
    SlotCutout,
    TextFeature,
    VentPattern,
)
from app.cad_v2.schemas.patterns import (
    CircularPattern,
    CustomPattern,
    GridPattern,
    LinearPattern,
    Pattern,
    PatternedFeature,
    PatternPresets,
    PatternType,
)
from app.cad_v2.schemas.spatial import (
    AbsolutePosition,
    AlignedPosition,
    Alignment2D,
    Alignment3D,
    AlignWithConstraint,
    CenterBetweenConstraint,
    DepthAlignment,
    HorizontalAlignment,
    LayoutHint,
    Margin,
    MaxDistanceConstraint,
    MinDistanceConstraint,
    Position,
    RelativePosition,
    SpatialConstraint,
    VerticalAlignment,
    WallPosition,
)

__all__ = [
    # Base types
    "Axis",
    "BoundingBox",
    "Dimension",
    "Point2D",
    "Point3D",
    "Rotation",
    "Tolerance",
    "Unit",
    "Vector3D",
    # Component types
    "ComponentCategory",
    "ComponentDefinition",
    "ComponentMount",
    "ComponentRef",
    "KeepoutZone",
    "MountingHole",
    "MountingType",
    "PortDefinition",
    "PortExposure",
    "StandoffSpec",
    "StandoffType",
    # Enclosure types
    "EnclosureSpec",
    "LidSpec",
    "LidType",
    "MountingTabSpec",
    "ScrewSpec",
    "SnapFitSpec",
    "VentilationSpec",
    "WallSide",
    "WallSpec",
    # Feature types
    "BaseCutout",
    "ButtonCutout",
    "CircleCutout",
    "CutoutShape",
    "CutoutSpec",
    "DisplayCutout",
    "Feature",
    "FeatureType",
    "MountingHoleFeature",
    "OvalCutout",
    "PolygonCutout",
    "PortCutout",
    "RectangleCutout",
    "SlotCutout",
    "TextFeature",
    "VentPattern",
    # Pattern types
    "CircularPattern",
    "CustomPattern",
    "GridPattern",
    "LinearPattern",
    "Pattern",
    "PatternedFeature",
    "PatternPresets",
    "PatternType",
    # Spatial types
    "AbsolutePosition",
    "AlignedPosition",
    "Alignment2D",
    "Alignment3D",
    "AlignWithConstraint",
    "CenterBetweenConstraint",
    "DepthAlignment",
    "HorizontalAlignment",
    "LayoutHint",
    "Margin",
    "MaxDistanceConstraint",
    "MinDistanceConstraint",
    "Position",
    "RelativePosition",
    "SpatialConstraint",
    "VerticalAlignment",
    "WallPosition",
]
